<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Formster.Application\Formster.Application.csproj" />
      <ProjectReference Include="..\Formster.Domain\Formster.Domain.csproj" />
    </ItemGroup>

</Project>
