name: Client CI Workflow

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  formster-client:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Formster.Client
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build application
        run: npm run build